### ISSUE TITLE
Can this be tagged?

### ISSUE THREAD

**Issue by WouterSioen** [KnpLabs/symfony2-autocomplete#21]
I want to create a homebrew formula from this, to be able to install symfony autocomplete trough homebrew. The repo needs a tag though, to be able to create this.

**Comment by pilot** [comment]
https://github.com/KnpLabs/symfony2-autocomplete/releases/tag/0.1

**Comment by weaverryan** [comment]
Sweet! Fast response Pilot :)

**Comment by WouterSioen** [comment]
Thanks!
