### ISSUE TITLE
Breaks scp autocomplete

### ISSUE THREAD

**Issue by aurelijusrozenas** [KnpLabs/symfony2-autocomplete#25]
Steps to reproduce:
- enable symfony completion
- type `scp myserver:`
- press `tab`
- this will remove `myserver:` and you will be left with `scp /`

**Comment by weaverryan** [comment]
I can't repeat this locally - I'm just left with `scp myserver:` when I hit tab. Is there something else needed to reproduce this?

**Comment by aurelijusrozenas** [comment]
If you type `scp myserver:/` and press tab twice does this list available files on server. `myserver` should a valid server in your ssh config and that you can ssh in with your ssh key not with password. Sorry if that was not clear.

**Comment by weaverryan** [comment]
Hi there!

I'm closing this as we've deprecated this library in favor of https://github.com/bamarni/symfony-console-autocomplete. Hopefully that will work well for you!

Cheers!
